package nezam;
// Generated Aug 28, 2017 11:22:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Amuzeshi generated by hbm2java
 */
public class Amuzeshi  implements java.io.Serializable {


     private int id;
     private String name;
     private Date sdate;
     private Date fdate;
     private String period;
     private String place;
     private String mojaveznumber;
     private Date dmojavez;
     private Date dazmun;
     private String teachername;
     private String parvaneteacher;
     private String sazman;
     private String number;
     private Integer idMain;

    public Amuzeshi() {
    }

	
    public Amuzeshi(int id) {
        this.id = id;
    }
    public Amuzeshi( String name,String number, Date sdate, Date fdate, String period, String place, String mojaveznumber, Date dmojavez, Date dazmun, String teachername, String parvaneteacher, String sazman, Integer idMain) {
       
       this.name = name;
       this.number=number;
       this.sdate = sdate;
       this.fdate = fdate;
       this.period = period;
       this.place = place;
       this.mojaveznumber = mojaveznumber;
       this.dmojavez = dmojavez;
       this.dazmun = dazmun;
       this.teachername = teachername;
       this.parvaneteacher = parvaneteacher;
       this.sazman = sazman;
       this.idMain = idMain;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
     public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public Date getSdate() {
        return this.sdate;
    }
    
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }
    public Date getFdate() {
        return this.fdate;
    }
    
    public void setFdate(Date fdate) {
        this.fdate = fdate;
    }
    public String getPeriod() {
        return this.period;
    }
    
    public void setPeriod(String period) {
        this.period = period;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public String getMojaveznumber() {
        return this.mojaveznumber;
    }
    
    public void setMojaveznumber(String mojaveznumber) {
        this.mojaveznumber = mojaveznumber;
    }
    public Date getDmojavez() {
        return this.dmojavez;
    }
    
    public void setDmojavez(Date dmojavez) {
        this.dmojavez = dmojavez;
    }
    public Date getDazmun() {
        return this.dazmun;
    }
    
    public void setDazmun(Date dazmun) {
        this.dazmun = dazmun;
    }
    public String getTeachername() {
        return this.teachername;
    }
    
    public void setTeachername(String teachername) {
        this.teachername = teachername;
    }
    public String getParvaneteacher() {
        return this.parvaneteacher;
    }
    
    public void setParvaneteacher(String parvaneteacher) {
        this.parvaneteacher = parvaneteacher;
    }
    public String getSazman() {
        return this.sazman;
    }
    
    public void setSazman(String sazman) {
        this.sazman = sazman;
    }
    public Integer getIdMain() {
        return this.idMain;
    }
    
    public void setIdMain(Integer idMain) {
        this.idMain = idMain;
    }




}


