package nezam;
// Generated Oct 20, 2017 11:00:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Finance generated by hbm2java
 */
public class Finance  implements java.io.Serializable {


     private int id;
     private Integer bedehkariamount;
     private String bedehkarikind;
     private Date pardakhtdate;
     private Date parvanedate;
     private Date registerdate;
     private Integer idMain;
     private String paye;
     private Integer ozviyatsaliyaneamount;
     private Double karkardamount;
     private Double darsad;
     private String fishnumber;
      private String checknumber;
     private String bankname;
     private Integer pay;
     private String paykind;
      private String extra;
      private Integer status;
      private String creator;
             

    public Finance() {
    }

	
    public Finance(int id) {
        this.id = id;
    }
  /*  public Finance(int id, Integer bedehkariamount, String bedehkarikind, Date pardakhtdate, Integer idMain, String paye, String year, String month, String day, String pyear, String pmonth, String pday, Integer ozviyatsaliyaneamount, Double karkardamount, Double darsad) {
       this.id = id;
       this.bedehkariamount = bedehkariamount;
       this.bedehkarikind = bedehkarikind;
       this.pardakhtdate = pardakhtdate;
       this.idMain = idMain;
       this.paye = paye;
      
       this.ozviyatsaliyaneamount = ozviyatsaliyaneamount;
       this.karkardamount = karkardamount;
       this.darsad = darsad;
    }
*/
    public Finance(int id,int value,int pay,Date regDate,Date payDate,String paykind,String fishnumber,String checknumber,String bank,String extra,String kind,int status,String creator)
    {
      
       bedehkariamount =value;
       bedehkarikind = kind;
       idMain = id;
       this.checknumber=checknumber;
       this.fishnumber=fishnumber;
       this.bankname=bank;
       this.pay=pay;
       this.pardakhtdate=payDate;
       this.paykind=paykind;
       this.registerdate=regDate;
       this.extra=extra;
       ozviyatsaliyaneamount = null;
       karkardamount = null;
       darsad = null;
       parvanedate=null;
       paye=null;
       this.status=status;
       this.creator=creator;
    }
     public Finance(int id,int value,int pay,Date regDate,Date payDate,String paykind,String fishnumber,String checknumber,String bank,String extra,String kind,String paye,int status,String creator)
    {
         bedehkariamount =value;
       bedehkarikind = kind;
       idMain = id;
       this.checknumber=checknumber;
       this.fishnumber=fishnumber;
       this.bankname=bank;
       this.pay=pay;
       this.pardakhtdate=payDate;
       this.paykind=paykind;
       this.registerdate=regDate;
       this.extra=extra;
       ozviyatsaliyaneamount = null;
       karkardamount = null;
       darsad = null;
       parvanedate=null;
       this.paye =paye;
       this.status=status;
       this.creator=creator;
               
    }
     public Finance(int id,int value,int pay,Date regDate,Date payDate,String paykind,String fishnumber,String checknumber,String bank,String extra,String kind,Date parvaneDate,int status,String creator)
     {
       bedehkariamount =value;
       bedehkarikind = kind;
       idMain = id;
       this.checknumber=checknumber;
       this.fishnumber=fishnumber;
       this.bankname=bank;
       this.pay=pay;
       this.pardakhtdate=payDate;
       this.paykind=paykind;
       this.registerdate=regDate;
       this.extra=extra;
       ozviyatsaliyaneamount = null;
       karkardamount = null;
       darsad = null;
       this.parvanedate=parvaneDate;
       this.paye =null;
       this.status=status;
       this.creator=creator;
     }
     public Finance(int id,int value,int pay,Date regDate,Date payDate,String paykind,String fishnumber,String checknumber,String bank,String extra,String kind,int ozviyatSalahiyatAmount,double karkard,double darsad,int status,String creator)
     {
       bedehkariamount =value;
       bedehkarikind = kind;
       idMain = id;
       this.checknumber=checknumber;
       this.fishnumber=fishnumber;
       this.bankname=bank;
       this.pay=pay;
       this.pardakhtdate=payDate;
       this.paykind=paykind;
       this.registerdate=regDate;
       this.extra=extra;
       this.ozviyatsaliyaneamount=ozviyatSalahiyatAmount;
       this.karkardamount=karkard;
       this.darsad=darsad;
       this.parvanedate=null;
       this.paye =null;
       this.status=status;
       this.creator=creator;
     }
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getBedehkariamount() {
        return this.bedehkariamount;
    }
    
    public void setBedehkariamount(Integer bedehkariamount) {
        this.bedehkariamount = bedehkariamount;
    }
    public String getBedehkarikind() {
        return this.bedehkarikind;
    }
    
    public void setBedehkarikind(String bedehkarikind) {
        this.bedehkarikind = bedehkarikind;
    }
    public Date getPardakhtdate() {
        return this.pardakhtdate;
    }
    
    public void setPardakhtdate(Date pardakhtdate) {
        this.pardakhtdate = pardakhtdate;
    }
     public Date getRegisterdate() {
        return this.registerdate;
    }
    
    public void setRegisterdate(Date registerdate) {
        this.registerdate=registerdate;
    }
     public Date getParvanedate() {
        return this.parvanedate;
    }
    
    public void setParvanedate(Date parvanedate) {
        this.parvanedate=parvanedate;
    }
    public Integer getIdMain() {
        return this.idMain;
    }
    
    public void setIdMain(Integer idMain) {
        this.idMain = idMain;
    }
    public String getPaye() {
        return this.paye;
    }
    
    public void setPaye(String paye) {
        this.paye = paye;
    }
  
    public Integer getOzviyatsaliyaneamount() {
        return this.ozviyatsaliyaneamount;
    }
    
    public void setOzviyatsaliyaneamount(Integer ozviyatsaliyaneamount) {
        this.ozviyatsaliyaneamount = ozviyatsaliyaneamount;
    }
    public Double getKarkardamount() {
        return this.karkardamount;
    }
    
    public void setKarkardamount(Double karkardamount) {
        this.karkardamount = karkardamount;
    }
    public Double getDarsad() {
        return this.darsad;
    }
    
    public void setDarsad(Double darsad) {
        this.darsad = darsad;
    }

   public Integer getPay() {
        return this.pay;
               
    }
    
    public void setPay(Integer pay) {
        this.pay=pay;
    }
     public String getfishnumber() {
        return this.fishnumber;
    }
    
    public void setfishnumber(String fishnumber) {
        this.fishnumber=fishnumber;
        
    }
     public String getchecknumber() {
        return this.checknumber;
    }
    
    public void setchecknumber(String checknumber) {
        this.checknumber=checknumber;
        
    }
     public String getbankname() {
        return this.bankname;
    }
    
    public void setbankname(String bankname) {
        this.bankname=bankname;
    }
      public String getpaykind() {
        return this.paykind;
    }
    
    public void setpaykind(String paykind) {
        this.paykind=paykind;
    }
     public String getextra() {
        return this.extra;
    }
    
    public void setextra(String extra) {
        this.extra=extra;
    }
        public int getstatus() {
        return this.status;
    }
    
    public void setstatus(int status) {
        this.status=status;
    }
    
         public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator=creator;
    }


}


