package nezam;
// Generated Aug 28, 2017 11:22:06 PM by Hibernate Tools 4.3.1



/**
 * Main generated by hbm2java
 */
public class Main  implements java.io.Serializable {


     private int id;
     private String lname;
     private String fname;
     private String latin;
     private String fathername;
     private String dofbirth;
     private String melicode;
     private String identitycardnumber;
     private String uniname;
     private String major;
     private String majorcode;
     private String hphone;
     private String mphone;
     private String notes;
     private String religion;
     private String membershipnumber;
     private String licensenumber;
     private String paye;
     private String archivecode;
     private String dsendinquiry;
     private String numbersendletter;
     private String dreceivedinquiry;
     private String ozviyattype;
     private String dtmdidozviyat;
     private String address;
     private String single;
     private String postalcode;
     private String cofbirth;
     private String ozviyatdate;
     private String sex;
     private String gerayesh;
     private String denduni;
     private String addressuni;
     private String dtest1;
     private String dtest2;
     private String dtest3;
     private String dsodur1;
     private String dsodur2;
     private String dsodur3;
     private String dtamdid;
     private String dendetebar;
     private String jobplace;
     private String jobaddress;
     private String jobtell;
     private String sarbazi;
     private String nezaratshiraz;
     private String documentshiraz;
     private String nezaratbonyad;
     private String documentbonyad;
     private String nezaratsadra;
     private String documentsadra;
     private String nezaratshahrestan;
     private String documentshahrestan;
     private String totalaverage;
     private String savabegh;
     private String dqualification;
     private String typequalifucation;
     private String performancequalification;
     private String supervisionqualification;
     private String ozviyatdocument;
     private String madrakejra;
     private String codemadrakejra;
     private String dsalahiyatejra;
     private String dsalahiyatnezarat;
     private String madraknezarat;
     private String dateinputinfo;
     private String fishnumber;
     private String fishdate;
     private String semat;
     private String teluni;
     private String sabeghe;
     private String image;
     private String bio;
     private String letter;
     private String denteghali;
     private String performance;
     private String docejra;



    public Main() {
    }

	
    public Main(int id) {
        this.id = id;
    }
    public Main (int id,String lname,String fname,String fatherName,String mcode,String mphone)
    {
       this.id = id;
       this.lname = lname;
       this.fname = fname;
       this.latin = null;
       this.fathername = fatherName;
       this.dofbirth = null;
       this.melicode = mcode;
       this.identitycardnumber = null;
       this.uniname = null;
       this.major = null;
       this.majorcode = null;
       this.hphone = null;
       this.mphone = mphone;
       this.notes = null;
       this.religion = null;
       this.membershipnumber = null;
       this.licensenumber = null;
       this.paye = null;
       this.archivecode = null;
       this.dsendinquiry = null;
       this.numbersendletter = null;
       this.dreceivedinquiry = null;
       this.ozviyattype = null;
       this.dtmdidozviyat = null;
       this.address = null;
       this.single = null;
       this.postalcode = null;
       this.cofbirth = null;
       this.ozviyatdate = null;
       this.sex = null;
       this.gerayesh = null;
       this.denduni = null;
       this.addressuni = null;
       this.dtest1 = null;
       this.dtest2 = null;
       this.dtest3 = null;
       this.dsodur1 = null;
       this.dsodur2 = null;
       this.dsodur3 = null;
       this.dtamdid = null;
       this.dendetebar = null;
       this.jobplace = null;
       this.jobaddress = null;
       this.jobtell = null;
       this.sarbazi = null;
       this.nezaratshiraz = null;
       this.documentshiraz = null;
       this.nezaratbonyad = nezaratbonyad;
       this.documentbonyad = documentbonyad;
       this.nezaratsadra = nezaratsadra;
       this.documentsadra = documentsadra;
       this.nezaratshahrestan = nezaratshahrestan;
       this.documentshahrestan = documentshahrestan;
       this.totalaverage = totalaverage;
       this.savabegh = savabegh;
       this.dqualification = dqualification;
       this.typequalifucation = typequalifucation;
       this.performancequalification = performancequalification;
       this.supervisionqualification = supervisionqualification;
       this.ozviyatdocument = ozviyatdocument;
       this.madrakejra = madrakejra;
       this.codemadrakejra = codemadrakejra;
       this.dsalahiyatejra = dsalahiyatejra;
       this.dsalahiyatnezarat = dsalahiyatnezarat;
       this.madraknezarat = madraknezarat;
       this.dateinputinfo = dateinputinfo;
       this.fishnumber = fishnumber;
       this.fishdate = fishdate;
       this.semat = semat;
       this.teluni = teluni;
       this.sabeghe = sabeghe;
       this.image = image;
       this.bio = bio;
    }
    public Main(int id, String lname, String fname, String latin, String fathername, String dofbirth, String melicode, String identitycardnumber, String uniname, String major, String majorcode, String hphone, String mphone, String notes, String religion, String membershipnumber, String licensenumber, String paye, String archivecode, String dsendinquiry, String numbersendletter, String dreceivedinquiry, String ozviyattype, String dtmdidozviyat, String address, String single, String postalcode, String cofbirth, String ozviyatdate, String sex, String gerayesh, String denduni, String addressuni, String dtest1, String dtest2, String dtest3, String dsodur1, String dsodur2, String dsodur3, String dtamdid, String dendetebar, String jobplace, String jobaddress, String jobtell, String sarbazi, String nezaratshiraz, String documentshiraz, String nezaratbonyad, String documentbonyad, String nezaratsadra, String documentsadra, String nezaratshahrestan, String documentshahrestan, String totalaverage, String savabegh, String dqualification, String typequalifucation, String performancequalification, String supervisionqualification, String ozviyatdocument, String madrakejra, String codemadrakejra, String dsalahiyatejra, String dsalahiyatnezarat, String madraknezarat, String dateinputinfo, String fishnumber, String fishdate, String semat, String teluni, String sabeghe, String image, String bio,String performance) {
       this.id = id;
       this.lname = lname;
       this.fname = fname;
       this.latin = latin;
       this.fathername = fathername;
       this.dofbirth = dofbirth;
       this.melicode = melicode;
       this.identitycardnumber = identitycardnumber;
       this.uniname = uniname;
       this.major = major;
       this.majorcode = majorcode;
       this.hphone = hphone;
       this.mphone = mphone;
       this.notes = notes;
       this.religion = religion;
       this.membershipnumber = membershipnumber;
       this.licensenumber = licensenumber;
       this.paye = paye;
       this.archivecode = archivecode;
       this.dsendinquiry = dsendinquiry;
       this.numbersendletter = numbersendletter;
       this.dreceivedinquiry = dreceivedinquiry;
       this.ozviyattype = ozviyattype;
       this.dtmdidozviyat = dtmdidozviyat;
       this.address = address;
       this.single = single;
       this.postalcode = postalcode;
       this.cofbirth = cofbirth;
       this.ozviyatdate = ozviyatdate;
       this.sex = sex;
       this.gerayesh = gerayesh;
       this.denduni = denduni;
       this.addressuni = addressuni;
       this.dtest1 = dtest1;
       this.dtest2 = dtest2;
       this.dtest3 = dtest3;
       this.dsodur1 = dsodur1;
       this.dsodur2 = dsodur2;
       this.dsodur3 = dsodur3;
       this.dtamdid = dtamdid;
       this.dendetebar = dendetebar;
       this.jobplace = jobplace;
       this.jobaddress = jobaddress;
       this.jobtell = jobtell;
       this.sarbazi = sarbazi;
       this.nezaratshiraz = nezaratshiraz;
       this.documentshiraz = documentshiraz;
       this.nezaratbonyad = nezaratbonyad;
       this.documentbonyad = documentbonyad;
       this.nezaratsadra = nezaratsadra;
       this.documentsadra = documentsadra;
       this.nezaratshahrestan = nezaratshahrestan;
       this.documentshahrestan = documentshahrestan;
       this.totalaverage = totalaverage;
       this.savabegh = savabegh;
       this.dqualification = dqualification;
       this.typequalifucation = typequalifucation;
       this.performancequalification = performancequalification;
       this.supervisionqualification = supervisionqualification;
       this.ozviyatdocument = ozviyatdocument;
       this.madrakejra = madrakejra;
       this.codemadrakejra = codemadrakejra;
       this.dsalahiyatejra = dsalahiyatejra;
       this.dsalahiyatnezarat = dsalahiyatnezarat;
       this.madraknezarat = madraknezarat;
       this.dateinputinfo = dateinputinfo;
       this.fishnumber = fishnumber;
       this.fishdate = fishdate;
       this.semat = semat;
       this.teluni = teluni;
       this.sabeghe = sabeghe;
       this.image = image;
       this.bio = bio;
       this.performance=performance;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLatin() {
        return this.latin;
    }
    
    public void setLatin(String latin) {
        this.latin = latin;
    }
    public String getFathername() {
        return this.fathername;
    }
    
    public void setFathername(String fathername) {
        this.fathername = fathername;
    }
    public String getDofbirth() {
        return this.dofbirth;
    }
    
    public void setDofbirth(String dofbirth) {
        this.dofbirth = dofbirth;
    }
    public String getMelicode() {
        return this.melicode;
    }
    
    public void setMelicode(String melicode) {
        this.melicode = melicode;
    }
    public String getIdentitycardnumber() {
        return this.identitycardnumber;
    }
    
    public void setIdentitycardnumber(String identitycardnumber) {
        this.identitycardnumber = identitycardnumber;
    }
    public String getUniname() {
        return this.uniname;
    }
    
    public void setUniname(String uniname) {
        this.uniname = uniname;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    public String getMajorcode() {
        return this.majorcode;
    }
    
    public void setMajorcode(String majorcode) {
        this.majorcode = majorcode;
    }
    public String getHphone() {
        return this.hphone;
    }
    
    public void setHphone(String hphone) {
        this.hphone = hphone;
    }
    public String getMphone() {
        return this.mphone;
    }
    
    public void setMphone(String mphone) {
        this.mphone = mphone;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getMembershipnumber() {
        return this.membershipnumber;
    }
    
    public void setMembershipnumber(String membershipnumber) {
        this.membershipnumber = membershipnumber;
    }
    public String getLicensenumber() {
        return this.licensenumber;
    }
    
    public void setLicensenumber(String licensenumber) {
        this.licensenumber = licensenumber;
    }
    public String getPaye() {
        return this.paye;
    }
    
    public void setPaye(String paye) {
        this.paye = paye;
    }
    public String getArchivecode() {
        return this.archivecode;
    }
    
    public void setArchivecode(String archivecode) {
        this.archivecode = archivecode;
    }
    public String getDsendinquiry() {
        return this.dsendinquiry;
    }
    
    public void setDsendinquiry(String dsendinquiry) {
        this.dsendinquiry = dsendinquiry;
    }
    public String getNumbersendletter() {
        return this.numbersendletter;
    }
    
    public void setNumbersendletter(String numbersendletter) {
        this.numbersendletter = numbersendletter;
    }
    public String getDreceivedinquiry() {
        return this.dreceivedinquiry;
    }
    
    public void setDreceivedinquiry(String dreceivedinquiry) {
        this.dreceivedinquiry = dreceivedinquiry;
    }
    public String getOzviyattype() {
        return this.ozviyattype;
    }
    
    public void setOzviyattype(String ozviyattype) {
        this.ozviyattype = ozviyattype;
    }
    public String getDtmdidozviyat() {
        return this.dtmdidozviyat;
    }
    
    public void setDtmdidozviyat(String dtmdidozviyat) {
        this.dtmdidozviyat = dtmdidozviyat;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getSingle() {
        return this.single;
    }
    
    public void setSingle(String single) {
        this.single = single;
    }
    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }
    public String getCofbirth() {
        return this.cofbirth;
    }
    
    public void setCofbirth(String cofbirth) {
        this.cofbirth = cofbirth;
    }
    public String getOzviyatdate() {
        return this.ozviyatdate;
    }
    
    public void setOzviyatdate(String ozviyatdate) {
        this.ozviyatdate = ozviyatdate;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getGerayesh() {
        return this.gerayesh;
    }
    
    public void setGerayesh(String gerayesh) {
        this.gerayesh = gerayesh;
    }
    public String getDenduni() {
        return this.denduni;
    }
    
    public void setDenduni(String denduni) {
        this.denduni = denduni;
    }
    public String getAddressuni() {
        return this.addressuni;
    }
    
    public void setAddressuni(String addressuni) {
        this.addressuni = addressuni;
    }
    public String getDtest1() {
        return this.dtest1;
    }
    
    public void setDtest1(String dtest1) {
        this.dtest1 = dtest1;
    }
    public String getDtest2() {
        return this.dtest2;
    }
    
    public void setDtest2(String dtest2) {
        this.dtest2 = dtest2;
    }
    public String getDtest3() {
        return this.dtest3;
    }
    
    public void setDtest3(String dtest3) {
        this.dtest3 = dtest3;
    }
    public String getDsodur1() {
        return this.dsodur1;
    }
    
    public void setDsodur1(String dsodur1) {
        this.dsodur1 = dsodur1;
    }
    public String getDsodur2() {
        return this.dsodur2;
    }
    
    public void setDsodur2(String dsodur2) {
        this.dsodur2 = dsodur2;
    }
    public String getDsodur3() {
        return this.dsodur3;
    }
    
    public void setDsodur3(String dsodur3) {
        this.dsodur3 = dsodur3;
    }
    public String getDtamdid() {
        return this.dtamdid;
    }
    
    public void setDtamdid(String dtamdid) {
        this.dtamdid = dtamdid;
    }
    public String getDendetebar() {
        return this.dendetebar;
    }
    
    public void setDendetebar(String dendetebar) {
        this.dendetebar = dendetebar;
    }
    public String getJobplace() {
        return this.jobplace;
    }
    
    public void setJobplace(String jobplace) {
        this.jobplace = jobplace;
    }
    public String getJobaddress() {
        return this.jobaddress;
    }
    
    public void setJobaddress(String jobaddress) {
        this.jobaddress = jobaddress;
    }
    public String getJobtell() {
        return this.jobtell;
    }
    
    public void setJobtell(String jobtell) {
        this.jobtell = jobtell;
    }
    public String getSarbazi() {
        return this.sarbazi;
    }
    
    public void setSarbazi(String sarbazi) {
        this.sarbazi = sarbazi;
    }
    public String getNezaratshiraz() {
        return this.nezaratshiraz;
    }
    
    public void setNezaratshiraz(String nezaratshiraz) {
        this.nezaratshiraz = nezaratshiraz;
    }
    public String getDocumentshiraz() {
        return this.documentshiraz;
    }
    
    public void setDocumentshiraz(String documentshiraz) {
        this.documentshiraz = documentshiraz;
    }
    public String getNezaratbonyad() {
        return this.nezaratbonyad;
    }
    
    public void setNezaratbonyad(String nezaratbonyad) {
        this.nezaratbonyad = nezaratbonyad;
    }
    public String getDocumentbonyad() {
        return this.documentbonyad;
    }
    
    public void setDocumentbonyad(String documentbonyad) {
        this.documentbonyad = documentbonyad;
    }
    public String getNezaratsadra() {
        return this.nezaratsadra;
    }
    
    public void setNezaratsadra(String nezaratsadra) {
        this.nezaratsadra = nezaratsadra;
    }
    public String getDocumentsadra() {
        return this.documentsadra;
    }
    
    public void setDocumentsadra(String documentsadra) {
        this.documentsadra = documentsadra;
    }
    public String getNezaratshahrestan() {
        return this.nezaratshahrestan;
    }
    
    public void setNezaratshahrestan(String nezaratshahrestan) {
        this.nezaratshahrestan = nezaratshahrestan;
    }
    public String getDocumentshahrestan() {
        return this.documentshahrestan;
    }
    
    public void setDocumentshahrestan(String documentshahrestan) {
        this.documentshahrestan = documentshahrestan;
    }
    public String getTotalaverage() {
        return this.totalaverage;
    }
    
    public void setTotalaverage(String totalaverage) {
        this.totalaverage = totalaverage;
    }
    public String getSavabegh() {
        return this.savabegh;
    }
    
    public void setSavabegh(String savabegh) {
        this.savabegh = savabegh;
    }
    public String getDqualification() {
        return this.dqualification;
    }
    
    public void setDqualification(String dqualification) {
        this.dqualification = dqualification;
    }
    public String getTypequalifucation() {
        return this.typequalifucation;
    }
    
    public void setTypequalifucation(String typequalifucation) {
        this.typequalifucation = typequalifucation;
    }
    public String getPerformancequalification() {
        return this.performancequalification;
    }
    
    public void setPerformancequalification(String performancequalification) {
        this.performancequalification = performancequalification;
    }
    public String getSupervisionqualification() {
        return this.supervisionqualification;
    }
    
    public void setSupervisionqualification(String supervisionqualification) {
        this.supervisionqualification = supervisionqualification;
    }
    public String getOzviyatdocument() {
        return this.ozviyatdocument;
    }
    
    public void setOzviyatdocument(String ozviyatdocument) {
        this.ozviyatdocument = ozviyatdocument;
    }
    public String getMadrakejra() {
        return this.madrakejra;
    }
    
    public void setMadrakejra(String madrakejra) {
        this.madrakejra = madrakejra;
    }
    public String getCodemadrakejra() {
        return this.codemadrakejra;
    }
    
    public void setCodemadrakejra(String codemadrakejra) {
        this.codemadrakejra = codemadrakejra;
    }
    public String getDsalahiyatejra() {
        return this.dsalahiyatejra;
    }
    
    public void setDsalahiyatejra(String dsalahiyatejra) {
        this.dsalahiyatejra = dsalahiyatejra;
    }
    public String getDsalahiyatnezarat() {
        return this.dsalahiyatnezarat;
    }
    
    public void setDsalahiyatnezarat(String dsalahiyatnezarat) {
        this.dsalahiyatnezarat = dsalahiyatnezarat;
    }
    public String getMadraknezarat() {
        return this.madraknezarat;
    }
    
    public void setMadraknezarat(String madraknezarat) {
        this.madraknezarat = madraknezarat;
    }
    public String getDateinputinfo() {
        return this.dateinputinfo;
    }
    
    public void setDateinputinfo(String dateinputinfo) {
        this.dateinputinfo = dateinputinfo;
    }
    public String getFishnumber() {
        return this.fishnumber;
    }
    
    public void setFishnumber(String fishnumber) {
        this.fishnumber = fishnumber;
    }
    public String getFishdate() {
        return this.fishdate;
    }
    
    public void setFishdate(String fishdate) {
        this.fishdate = fishdate;
    }
    public String getSemat() {
        return this.semat;
    }
    
    public void setSemat(String semat) {
        this.semat = semat;
    }
    public String getTeluni() {
        return this.teluni;
    }
    
    public void setTeluni(String teluni) {
        this.teluni = teluni;
    }
    public String getSabeghe() {
        return this.sabeghe;
    }
    
    public void setSabeghe(String sabeghe) {
        this.sabeghe = sabeghe;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getBio() { 
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }
     public String getLetter() {
        return this.letter;
    }
    
    public void setLetter(String letter) {
        this.letter = letter;
    }
    
  public String getDenteghali() {
        return this.denteghali;
    }
    
    public void setDenteghali(String denteghali) {
        this.denteghali=denteghali;
    }
     public String getPerformance() {
        return this.performance;
    }
    
    public void setPerformance(String performance) {
        this.performance = performance;}
    
      public String getdocejra() {
        return this.docejra;
    }
    
    public void setdocejra(String docejra) {
        this.docejra = docejra;}

  
}


