package nezam;
// Generated Mar 17, 2018 1:36:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Majma generated by hbm2java
 */
public class Majma  implements java.io.Serializable {


     private int id;
     private Date dbargozari;
     private String result;
     private Integer idMain;

    public Majma() {
    }

	
    public Majma(int id) {
        this.id = id;
    }
    public Majma(Date dbargozari, String result, Integer idMain) {
       
       this.dbargozari = dbargozari;
       this.result = result;
       this.idMain = idMain;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getDbargozari() {
        return this.dbargozari;
    }
    
    public void setDbargozari(Date dbargozari) {
        this.dbargozari = dbargozari;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public Integer getIdMain() {
        return this.idMain;
    }
    
    public void setIdMain(Integer idMain) {
        this.idMain = idMain;
    }




}


