package nezam;
// Generated Mar 17, 2018 1:36:23 PM by Hibernate Tools 4.3.1



/**
 * Sahmiye generated by hbm2java
 */
public class Sahmiye  implements java.io.Serializable {


     private Integer id;
     private String entire;
     private String part;
     private Integer idMain;
     private String year;
     private String loc;
     private String kind;
     

    public Sahmiye() {
    }

    public Sahmiye(String entire, String part, Integer idMain, String year,String loc,String kind) {
       this.entire = entire;
       this.part = part;
       this.idMain = idMain;
       this.year = year;
       this.loc=loc;
       this.kind=kind;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEntire() {
        return this.entire;
    }
    
    public void setEntire(String entire) {
        this.entire = entire;
    }
    public String getPart() {
        return this.part;
    }
    
    public void setPart(String part) {
        this.part = part;
    }
    public Integer getIdMain() {
        return this.idMain;
    }
    
    public void setIdMain(Integer idMain) {
        this.idMain = idMain;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
      public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
      public String getKind() {
        return this.kind;
    }
    
    public void setKind(String kind) {
        this.kind = kind;
    }




}


