package nezam;
// Generated Aug 28, 2017 11:22:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tajrobi generated by hbm2java
 */
public class Tajrobi  implements java.io.Serializable {


     private int id;
     private String name;
     private String lname;
     private String fname;
     private String shnumber;
     private String mcode;
     private String tyear;
     private String cposti;
     private String address;
     private String hphone;
     private String sphone;
     private String nparvane;
     private String paye;
     private String dsparvane;
     private String deparvane;
     private String hpsalane;
     private String cbayegani;
     private String ejraname;
     private String dejraname;

    public Tajrobi() {
    }

	
    public Tajrobi(int id) {
        this.id = id;
    }
    public Tajrobi(int id,String lname,String fname,String fatherName,String mcode,String mphone)
    {
       this.id = id;
       this.name = fname;
       this.lname = lname;
       this.fname = fatherName;
       this.shnumber = null;
       this.mcode = mcode;
       this.tyear = null;
       this.cposti = null;
       this.address = null;
       this.hphone = mphone;
       this.sphone = null;
       this.nparvane = null;
       this.paye = null;
       this.dsparvane = null;
       this.deparvane = null;
       this.hpsalane =null;
       this.cbayegani = null;
       this.ejraname = null;
       this.dejraname = null;
    }
    public Tajrobi(int id, String name, String lname, String fname, String shnumber, String mcode, String tyear, String cposti, String address, String hphone, String sphone, String nparvane, String paye, String dsparvane, String deparvane, String hpsalane, String cbayegani, String ejraname, String dejraname) {
       this.id = id;
       this.name = name;
       this.lname = lname;
       this.fname = fname;
       this.shnumber = shnumber;
       this.mcode = mcode;
       this.tyear = tyear;
       this.cposti = cposti;
       this.address = address;
       this.hphone = hphone;
       this.sphone = sphone;
       this.nparvane = nparvane;
       this.paye = paye;
       this.dsparvane = dsparvane;
       this.deparvane = deparvane;
       this.hpsalane = hpsalane;
       this.cbayegani = cbayegani;
       this.ejraname = ejraname;
       this.dejraname = dejraname;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getShnumber() {
        return this.shnumber;
    }
    
    public void setShnumber(String shnumber) {
        this.shnumber = shnumber;
    }
    public String getMcode() {
        return this.mcode;
    }
    
    public void setMcode(String mcode) {
        this.mcode = mcode;
    }
    public String getTyear() {
        return this.tyear;
    }
    
    public void setTyear(String tyear) {
        this.tyear = tyear;
    }
    public String getCposti() {
        return this.cposti;
    }
    
    public void setCposti(String cposti) {
        this.cposti = cposti;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getHphone() {
        return this.hphone;
    }
    
    public void setHphone(String hphone) {
        this.hphone = hphone;
    }
    public String getSphone() {
        return this.sphone;
    }
    
    public void setSphone(String sphone) {
        this.sphone = sphone;
    }
    public String getNparvane() {
        return this.nparvane;
    }
    
    public void setNparvane(String nparvane) {
        this.nparvane = nparvane;
    }
    public String getPaye() {
        return this.paye;
    }
    
    public void setPaye(String paye) {
        this.paye = paye;
    }
    public String getDsparvane() {
        return this.dsparvane;
    }
    
    public void setDsparvane(String dsparvane) {
        this.dsparvane = dsparvane;
    }
    public String getDeparvane() {
        return this.deparvane;
    }
    
    public void setDeparvane(String deparvane) {
        this.deparvane = deparvane;
    }
    public String getHpsalane() {
        return this.hpsalane;
    }
    
    public void setHpsalane(String hpsalane) {
        this.hpsalane = hpsalane;
    }
    public String getCbayegani() {
        return this.cbayegani;
    }
    
    public void setCbayegani(String cbayegani) {
        this.cbayegani = cbayegani;
    }
    public String getEjraname() {
        return this.ejraname;
    }
    
    public void setEjraname(String ejraname) {
        this.ejraname = ejraname;
    }
    public String getDejraname() {
        return this.dejraname;
    }
    
    public void setDejraname(String dejraname) {
        this.dejraname = dejraname;
    }




}


